networks:
  default:
    name: proxy
    external: true
services:
  openrefine:
    image: easypi/openrefine
    container_name: openrefine
    ports:
      - "3333:3333"
    volumes:
      - ./data:/data
    environment:
      - REFINE_INTERFACE=0.0.0.0
      - REFINE_PORT=3333
      - REFINE_MIN_MEMORY=1024M
      - REFINE_MEMORY=1024M
      - REFINE_DATA_DIR=/data
      - REFINE_EXTRA_OPTS=refine.headless=true
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
