name: ${STACK_NAME:-watchtower}
networks:
  service:
    name: ${SERVICE_NETWORK:-service}
    external: true
services:
  watchtower:
    image: nickfedor/watchtower
    container_name: watchtower
    restart: unless-stopped
    profiles:
      - ${SERVICE_PROFILE:-service}
    networks:
      - service
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      TZ: ${TZ:-America/Caracas}
      WATCHTOWER_CLEANUP: ${WATCHTOWER_CLEANUP:-true}
      WATCHTOWER_LABEL_ENABLE: ${WATCHTOWER_LABEL_ENABLE:-true}
      WATCHTOWER_INCLUDE_RESTARTING: ${WATCHTOWER_INCLUDE_RESTARTING:-true}
      WATCHTOWER_SCHEDULE: ${WATCHTOWER_SCHEDULE:-0 0 1 * * *}
    healthcheck:
      test: ["CMD", "/watchtower", "--health-check"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - glance.name=Watchtower
      - glance.icon=di:watchtower
      - glance.description=Watchtower is a tool for automating Docker container updates.
